"""Aggregate 1m BTC candles into intraday/overnight windows.

Inputs: ``data/raw/btc_1m/btc_1m_raw.csv`` generated by ``get_btc_1m_binance``.
Outputs: ``data/clean/btc_windows.csv`` with close-close, intraday, and
overnight returns plus realized variances.
"""

from __future__ import annotations

from datetime import time

import numpy as np
import pandas as pd
import pytz

from config.config import CLEAN_DIR, RAW_DIR, US_EQUITY_CLOSE_ET, US_EQUITY_OPEN_ET

ET = pytz.timezone("US/Eastern")


def _as_time(value: str) -> time:
    return pd.to_datetime(value).time()


def realized_variance(returns: pd.Series) -> float:
    return float(np.nansum(np.square(returns))) if not returns.empty else np.nan


def main() -> None:
    raw_path = RAW_DIR / "btc_1m" / "btc_1m_raw.csv"
    out_path = CLEAN_DIR / "btc_windows.csv"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    df = pd.read_csv(raw_path, parse_dates=["timestamp_utc"])
    if df.empty:
        raise SystemExit("No BTC candles found; run src/get_btc_1m_binance.py first")

    df["timestamp_et"] = df["timestamp_utc"].dt.tz_localize("UTC").dt.tz_convert(ET)
    df["date_et"] = df["timestamp_et"].dt.date
    df["time_et"] = df["timestamp_et"].dt.time

    open_time = _as_time(US_EQUITY_OPEN_ET)
    close_time = _as_time(US_EQUITY_CLOSE_ET)

    def last_before(time_cutoff):
        return (
            df[df["time_et"] <= time_cutoff]
            .groupby("date_et")
            .last()["close"]
            .rename("price")
        )

    intraday_open = last_before(open_time).rename("btc_open_intraday")
    intraday_close = last_before(close_time).rename("btc_close_intraday")
    daily_close = last_before(close_time).rename("btc_close_et")

    daily = pd.concat([intraday_open, intraday_close, daily_close], axis=1)
    daily = daily.reset_index().rename(columns={"date_et": "date"})
    daily["date"] = pd.to_datetime(daily["date"])
    daily.sort_values("date", inplace=True)
    daily["btc_prev_close_et"] = daily["btc_close_et"].shift(1)

    daily["ret_close_close"] = np.log(daily["btc_close_et"] / daily["btc_prev_close_et"])
    daily["ret_intraday"] = np.log(daily["btc_close_intraday"] / daily["btc_open_intraday"])
    daily["ret_overnight"] = daily["ret_close_close"] - daily["ret_intraday"]

    # Realized variance calculations
    df.sort_values("timestamp_et", inplace=True)
    df["log_return"] = np.log(df["close"].astype(float)).diff()
    df["date_next"] = df["date_et"].shift(-1)

    intraday_mask = df["time_et"].between(open_time, close_time)
    rv_intraday = (
        df[intraday_mask]
        .groupby(df["date_et"])
        ["log_return"]
        .apply(realized_variance)
        .rename("rv_intraday")
        .reset_index()
        .rename(columns={"date_et": "date"})
    )

    overnight_mask = ~intraday_mask
    rv_overnight = (
        df[overnight_mask]
        .groupby(df["date_et"])
        ["log_return"]
        .apply(realized_variance)
        .rename("rv_overnight")
        .reset_index()
        .rename(columns={"date_et": "date"})
    )

    daily = (
        daily.merge(rv_intraday, on="date", how="left")
        .merge(rv_overnight, on="date", how="left")
    )

    daily.to_csv(out_path, index=False)
    print(f"Saved BTC windows to {out_path}")


if __name__ == "__main__":
    main()
